FROM gradle:jdk17-graal as build

WORKDIR /app
COPY . .

RUN <<EOF
gradle bootJar
mv build/libs/*.jar app.jar
EOF

#CMD ["java", "-jar", "app.jar"]
#EXPOSE 8080

FROM eclipse-temurin:17-jre

WORKDIR /app
COPY --from=build /app/app.jar .

CMD ["java", "-jar", "app.jar"]
EXPOSE 8080

